runtime: python312
entrypoint: gunicorn -b :$PORT app:server

# 메모리 여유 필요 시 풀어주세요 (옵션)
# instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 2

env_variables:
  # --- 런타임/로깅 ---
  TZ: "Asia/Seoul"
  LOG_LEVEL: "INFO"

  # --- 실행/심볼 ---
  EXECUTE_TRADES: "true"
  SYMBOLS: "BTCUSDT,ETHUSDT"

  # --- 모델 ---
  GEMINI_MODEL: "gemini-2.5-flash-lite"
  USE_CALIBRATED_PROB: "true"              # ★ 명시
  PROB_CALIBRATION_PATH: "/tmp/trading_bot/calibration.json"
  CALIB_MIN_SAMPLES: "150"
  CALIB_BINS: "10"

  # --- 로그/GCS ---
  GCS_BUCKET: "tothemoon-v2-logs-vaulted-scholar-466013-r5-seoul"
  GCS_PREFIX: "trading_bot"

  # --- 리스크/게이팅 ---
  MIN_PROB: "0.65"
  PROB_RELAX_THRESHOLD: "0.78"
  RR_MIN: "1.2"
  RR_MIN_HIGH_PROB: "1.08"
  RR_EVAL_WITH_FEES: "true"              # ★ 패치-2로 활성화
  MAX_SPREAD_BPS: "1.5"
  HORIZON_MIN: "30"
  TIME_BARRIER_ENABLED: "true"
  MIN_VOL_FRAC: "0.0005"

  # --- MTF/쇼크/쿨다운 게이트(★ 모두 활성화) ---
  MTF_ALIGN_ENABLED: "true"
  MTF_RSI_LONG_MIN: "49"
  MTF_RSI_SHORT_MAX: "51"
  SHOCK_BPS: "30"
  SHOCK_ATR_MULT: "1.8"
  ENTRY_COOLDOWN_MIN: "10"

  # --- 손절/익절 ---
  ATR_MULT_SL: "1.2"
  ATR_MULT_TP: "2.2"
  TP_ORDER_TYPE: "LIMIT"                   # 필요 시 MARKET로 A/B
  SL_ORDER_TYPE: "STOP_MARKET"             # ★ STOP_LIMIT 시험시 변경
  SL_LIMIT_SLIPPAGE_BPS: "10"              # ★ STOP_LIMIT 사용 시만 관여

  # --- 집행/주문 ---
  ENTRY_MODE: "LIMIT"
  ENTRY_POST_ONLY: "true"                  # ★ 패치-1로 활성화
  LIMIT_TTL_SEC: "20"
  LIMIT_POLL_SEC: "1.0"
  LIMIT_MAX_REPRICES: "2"
  LIMIT_MAX_SLIPPAGE_BPS: "2.0"
  LIMIT_FAILOVER_TO_MARKET: "true"
  LIMIT_TTL_FALLBACK_TO_MARKET: "true"

  # --- BE 트레일링 ---
  BE_TRAILING_ENABLED: "true"
  BE_TRIGGER_R_MULT: "1.0"
  BE_OFFSET_TICKS: "2"

  # --- 포지션/사이징 --- #
  SIZE_MODE: "USDT"          # USDT | BALANCE_PCT
  RISK_BAL_PCT: "1.50"              # 지갑의 1.5% 사용
  SIZE_BAL_INCLUDE_UPNL: "false"    # 미실현손익 포함 여부 (true/false)
  RISK_USDT: "100"
  LEVERAGE: "5"
  MARGIN_TYPE: "ISOLATED"
  POSITION_MODE: "ONEWAY"
  POSITION_SIDE: "BOTH"
  VOL_SIZE_SCALING: "true"
  VOL_SCALAR_MIN: "0.5"
  VOL_SCALAR_MAX: "1.25"

  # --- 네트워킹 ---
  BINANCE_HTTP_TIMEOUT_MS: "10000"
  BINANCE_HTTP_RETRIES: "3"
  BINANCE_HTTP_BACKOFF_MS: "1000"

  # --- 수수료(bps) ---
  FEE_MAKER_BPS: "2.0"                     # ★ 패치-2로 사용
  FEE_TAKER_BPS: "4.0"

  # ───────── 프런트 리디렉션(옵션) ─────────
  FRONTEND_BASE_URL: ""                        # 배포 프런트엔드 URL (없으면 공백)
  # --- 로깅 ---
  LOG_DIR: "/tmp/trading_bot"
vpc_access_connector:
  name: projects/vaulted-scholar-466013-r5/locations/asia-northeast3/connectors/appengine-conn2
  egress_setting: all-traffic

handlers:
- url: /.*
  script: auto
